### ISSUE TITLE
Update Docker Hub, version

### ISSUE THREAD

**Issue by chris-scentregroup** [acoshift/revprox#3]
Can we please also get a new push to docker hub.

https://hub.docker.com/r/acoshift/revprox/tags/

Perhaps we can have master git push to latest tag and we can change https://github.com/acoshift/revprox/blob/master/main.go#L14 to 1.0.0 or the reverse.

Perhaps doing some CI/CD with CircleCI?

**Comment by acoshift** [comment]
Hi, I just change to version to 1.1.0 and pushed to docker hub.
For CI/CD I think I have to write some test first.

**Comment by chris-scentregroup** [comment]
Thanks! Would be nice to also have latest pushed to docker hub against master, fine to wait for the CI for that though.

**Comment by flaccid** [comment]
Here is an example (albeit a long one) doing build and push to docker hub in circle, https://github.com/flaccid/sitemap-crawler/blob/master/.circleci/config.yml.
